// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RZ0B8x64g_LSFwonv1hWXJ53MxCIykA',
    appId: '1:90390837114:web:d0bead9fac53caa2f148c3',
    messagingSenderId: '90390837114',
    projectId: 'cw06-bb5d5',
    authDomain: 'cw06-bb5d5.firebaseapp.com',
    storageBucket: 'cw06-bb5d5.firebasestorage.app',
    measurementId: 'G-16P67DGXSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAn_a5votaiO5d5ZWQW3IeKTWGElFdbFM',
    appId: '1:90390837114:android:ec2702c66b8b9865f148c3',
    messagingSenderId: '90390837114',
    projectId: 'cw06-bb5d5',
    storageBucket: 'cw06-bb5d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0k8zSNTf3J_-klKGXQTNsPeHAGN047w',
    appId: '1:90390837114:ios:e764bfe4bb664486f148c3',
    messagingSenderId: '90390837114',
    projectId: 'cw06-bb5d5',
    storageBucket: 'cw06-bb5d5.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0k8zSNTf3J_-klKGXQTNsPeHAGN047w',
    appId: '1:90390837114:ios:e764bfe4bb664486f148c3',
    messagingSenderId: '90390837114',
    projectId: 'cw06-bb5d5',
    storageBucket: 'cw06-bb5d5.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8RZ0B8x64g_LSFwonv1hWXJ53MxCIykA',
    appId: '1:90390837114:web:9b2a9c400548e94df148c3',
    messagingSenderId: '90390837114',
    projectId: 'cw06-bb5d5',
    authDomain: 'cw06-bb5d5.firebaseapp.com',
    storageBucket: 'cw06-bb5d5.firebasestorage.app',
    measurementId: 'G-GVQN9JF9RW',
  );

}